name: Enode Event

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    env:
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}-${{ vars.TF_WORKSPACE }}
      LAMBDA_FUNCTION_NAME: ${{ vars.AWS_LAMBDA_FUNCTION }}-${{ vars.TF_WORKSPACE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Credentionals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}                # Same with the lambda function region

      - name: Build Golang code
        working-directory: ${{ github.workspace }}  # Set the working directory to your Golang code directory
        run: |
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          go build -o bootstrap main.go

      - name: Zip Golang build files
        working-directory: ${{ github.workspace }}
        run: |
          zip -r enode-webhook-v1.zip .

      - name: Upload to AWS S3
        working-directory: ${{ github.workspace }}
        run: |
          bucket_name="${{ env.BUCKET_NAME }}"
          region="${{ env.AWS_REGION }}"
          
          # Upload the object to the S3 bucket
          aws s3 cp enode-webhook-v1.zip "s3://$bucket_name/$object_name"

        # Lambda function exists check required as some times terraform resources may
        # be down at all so in that case we don't want to update that function
        # or run next job named Update Lambda Function. We still somehow want to upload
        # zip to s3 as its independent of terraform resources which we did before.
      - name: Check if Lambda function exists
        id: lambda_check
        run: |
          lambda_function_name="${{ env.LAMBDA_FUNCTION_NAME }}"
          if aws lambda get-function --function-name "$lambda_function_name" >/dev/null 2>&1; then
            echo "::set-output name=function_exists::true"
          else
            echo "::set-output name=function_exists::false"
          fi

      - name: Update Lambda Function
        if: steps.lambda_check.outputs.function_exists == 'true'
        run: |
          lambda_function_name="${{ env.LAMBDA_FUNCTION_NAME }}"
          bucket_name="${{ env.BUCKET_NAME }}"
          object_name="enode-webhook-v1.zip"

          # Update the Lambda function code with the latest version from S3
          aws lambda update-function-code \
            --function-name "$lambda_function_name" \
            --s3-bucket "$bucket_name" \
            --s3-key "$object_name"